name: Dependency Sanity
on:
  pull_request:
    paths:
      - '**/pom.xml'
      - '**/build.gradle'
      - '**/build.gradle.kts'
permissions:
  pull-requests: write
  contents: read
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: lhein/dependency-sanity-action@main
        with:
          mode: diff
          fail-on: none
