name: Dependency Sanity
on:
  pull_request:
    paths: ['**/pom.xml']
permissions:
  pull-requests: write
  contents: read
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: lhein/dependency-sanity-action@v0.1.3
        with:
          mode: diff
          fail-on: none
